osx_image: xcode10.1
language: swift

branches:
  only:
    - master

stages:
  - name: test
  - name: beta
    if: (type == push) AND (branch == master) AND (commit_message =~ /^\[beta\]/)

cache:
  bundler: true
  cocoapods: true
  directories:
    - js/node_modules

install:
  - cd subtrees/the-blue-alliance-react && npm install && cd ../..
  - bundle install
  - bundle exec pod install --repo-update

before_script:
  - cp mock-Secrets.plist the-blue-alliance-ios/Secrets.plist
  - bundle exec fastlane setup_ci
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script: bundle exec fastlane scan --scheme tba-unit-tests
    # - script: bundle exec fastlane scan --scheme tba-ui-tests
    #   name: "UI Tests"
    - stage: beta
      script:
        - bundle exec fastlane setup_secrets
        - bundle exec fastlane beta_ci
