osx_image: xcode9.3
language: swift

branches:
  only:
  - master

cache:
  bundler: true
  cocoapods: true
  directories:
    - js/node_modules

install:
  - cd js && npm install && cd ..
  - bundle install
  - bundle exec pod install --repo-update
  - cp mock-GoogleService-Info.plist the-blue-alliance-ios/GoogleService-Info.plist

script:
  - bundle exec fastlane test
